#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$c = require_once __DIR__.'/container.php';

$application = new Application('Drink locator import command', '1.0.0');

$application->add(new \Bab\Command\ImportCommand($c['osrm_client'], $c['indexer'], $c['logger']));

$application->setDispatcher($c['dispatcher']);
$application->run();
