services:
    elasticsearch_data_provider:
        class: DrinkLocator\AppBundle\DataProvider\ElasticsearchDataProvider
        arguments: [ "@search.engine" ]
        tags:  [ { name: "api.data_provider", priority: 1 } ]

    search.engine:
        class: DrinkLocator\Elasticsearch\Engine
        arguments: [ "@elasticsearch.bar_or_pub.type", "@data_transformer.bar_or_pub", "@monolog.logger.search" ]

    elasticsearch.event_subscriber:
        class: DrinkLocator\Elasticsearch\EventSubscriber
        arguments: [ "@event_dispatcher", "@elasticsearch.bar_or_pub.type", "@data_transformer.bar_or_pub", "@monolog.logger.search" ]
        tags: [ { name: "kernel.event_subscriber" } ]

    elasticsearch.bar_or_pub.type:
        class: Elastica\Type
        public: false
        arguments: [ "@elasticsearch.bar_or_pub.index", "bar" ]

    elasticsearch.bar_or_pub.index:
        class: Elastica\Index
        public: false
        arguments: [ "@elasticsearch.client", "bars" ]

    elasticsearch.client:
        class: Elastica\Client
        public: false
        arguments: [{ "host": "%elasticsearch_host%", "port": "%elasticsearch_port%" }]

    data_transformer.bar_or_pub:
        class: DrinkLocator\Elasticsearch\DataTransformer\BarOrPub
        public: false

    # Monolog
    monolog.psr_log.processor:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags: [ { name: "monolog.processor" } ]

    monolog.web.processor:
        class: Symfony\Bridge\Monolog\Processor\WebProcessor
        tags: [ { name: "monolog.processor" }, { name: "kernel.event_listener", event: "kernel.request" } ]

    # Resources
    resource.bar_or_pub:
        parent:    "api.resource"
        arguments: [ "DrinkLocator\\Entity\\BarOrPub" ]
        tags:      [ { name: "api.resource" } ]

    resource.geo_coordinates:
        parent:    "api.resource"
        arguments: [ "DrinkLocator\\Entity\\GeoCoordinates" ]
        tags:      [ { name: "api.resource" } ]

    resource.postal_address:
        parent:    "api.resource"
        arguments: [ "DrinkLocator\\Entity\\PostalAddress" ]
        tags:      [ { name: "api.resource" } ]
